#!/usr/bin/env zsh
#
# === {{CMD}}
#
set -u -e -o pipefail

local +x ORIGINAL_ARGS="$@"
if [[ -z "$@" ]]; then
  local +x ACTION="watch"
else
  local +x ACTION="$1"; shift
fi

case "$ACTION" in

  watch)
    local +x CMD="da_css.cr scratch run"
    ${=CMD} || :
    process watch "-r src -r tmp/in -r specs" "$CMD"
    ;;

  run)
    sh_color ORANGE "=== {{Compiling}}..."
    my_crystal __ build tmp/in/scratch.cr -o tmp/out/scratch
    sh_color ORANGE "=== {{Running}}..."
    tmp/out/scratch
    sh_color ORANGE "=== {{Done}} ==="
    ;;

  *)
    echo "!!! Unknown arguments: $ORIGINAL_ARGS" >&2
    exit 1
    ;;

esac

