#!/usr/bin/env zsh
#
# === {{CMD}}
#
set -u -e -o pipefail

local +x ORIGINAL_ARGS="$@"
if [[ -z "$@" ]]; then
  local +x ACTION="watch"
else
  local +x ACTION=$1; shift
fi

case "$ACTION" in

  watch)
    mkdir -p tmp/in
    local +x CMD="da_css.cr specs run $@"
    sh_color ORANGE "=== {{Running}}: $CMD"
    ${=CMD} || :
    process watch "-r examples -r src -r specs -r bin -r sh -r tmp/in" "$CMD"
    ;;

  run)
    export DEV_BUILD=yes
    mkdir -p tmp/out
    case "${CHANGED_FILE:-}" in
      *"in/arg"*|*".css") : ;;
      *)
        sh_color ORANGE "=== {{Compiling}}..."
        my_crystal __ build specs/specs.cr -o tmp/out/specs
        ;;
    esac

    reset
    sh_color ORANGE "=== {{Running}}..."
    tmp/out/specs $(cat tmp/in/args tmp/in/arg 2>/dev/null || :) $@
    sh_color GREEN "=== {{DONE}} ==="
    ;;

  *)
    echo "!!! Unknown arguments: $ORIGINAL_ARGS" >&2
    exit 1
    ;;

esac

