#!/usr/bin/env zsh
#
# === {{CMD}}
#
set -u -e -o pipefail

local +x ORIGINAL_ARGS="$@"
if [[ -z "$@" ]]; then
  local +x ACTION=list
else
  local +x ACTION=$1; shift
fi

local +x LIST_TXT=src/da_style/list.txt
local +x LIST_FAMILY=src/da_style/list.family.txt
local +x LIST_NON_STANDARD=src/da_style/list.non.standard.txt

case "$ACTION" in

  diff)
    local +x TMP_FILE_1="$(mktemp)"
    local +x TMP_FILE_2="$(mktemp)"
    da_style.cr property-list latest > "$TMP_FILE_1"
    cat "$LIST_TXT" | sort | uniq  > "$TMP_FILE_2"
    diff --ignore-all-space "$TMP_FILE_1" "$TMP_FILE_2"
    rm -f "$TMP_FILE_1" "$TMP_FILE_2"
    ;;

  family)
    {
      IFS=$'\n'
      for line in $(cat "$LIST_TXT" | grep -- "-" | cut -d"-" -f1 | sort | uniq -c -d | tr -s " ") ; do
        local +x num=$line[(ws: :)1]
        local +x word=$line[(ws: :)2]
        if [[ "$num" -gt 2 && ! -z "$word" ]]; then
          echo $word
        fi
      done
    } > "$LIST_FAMILY"
    cat "$LIST_FAMILY"
    ;;

  latest)
    cd "$THIS_DIR"
    {
      lynx --dump "https://www.w3.org/TR/CSS2/propidx.html" | grep -Po "]'\K[^']+"
      cat "$LIST_NON_STANDARD"
    } | sort | uniq | grep -v -P '^$'
    ;;

  list)
    if my_fs a-is-younger-than-b "$LIST_TXT" "$LIST_FAMILY" ; then
      da_style.cr property-list family &>/dev/null
    fi
    cat "$LIST_TXT"
    ;;

  *)
    echo "!!! Unknown arguments: $ORIGINAL_ARGS" >&2
    exit 1
    ;;

esac

