#!/usr/bin/env zsh
#
# === {{CMD}} w3|used
# === {{CMD}} samples [all]
# === {{CMD}} samples continue property-name
# === {{CMD}} samples save-to-specs [continue]
#
set -u -e -o pipefail

local +x ORIGINAL_ARGS="$@"
if [[ -z "$@" ]]; then
  local +x ACTION=list
else
  local +x ACTION=$1; shift
fi

local +x LIST_TXT=src/da_style/list.txt
local +x LIST_FAMILY=src/da_style/list.family.txt
local +x LIST_NON_STANDARD=src/da_style/list.non.standard.txt

case "$ACTION" in

  samples)
    cd "$THIS_DIR"

    if [[ -z "$@" ]]; then
      ACTION="all"
    else
      ACTION="$1"; shift
    fi
    local +x continue=""

    print-page () {
      local +x name="$1"; shift
      echo "/* $name */"

      local +x content="$(lynx --dump --width 1024 "https://developer.mozilla.org/en-US/docs/Web/CSS/$name" || :)"
      if [[ -z "$content" ]]; then
        echo "!!! Failed to get html page for: $name" >&2
        return 2
      fi
      echo "$content" | grep -P "^/\*.+\*/$|^[a-z].+:.+;$" | sed 's/https\?:\///g'
    }

    local +x save=""
    case "$ACTION" in
      continue)
        local +x continue="$1"; shift
        ;;

      get)
        print-page $@
        return 0
        ;;

      all)
        :
        ;;

      save)
        local +x name="$1"; shift
        echo "=== Saving: $name" >&2
        print-page $name > specs/parser/samples/${name}.css
        return 0
        ;;

      save-to-specs)
        local +x save=true
        mkdir -p specs/parser/samples
        if [[ ! -z "$@" ]]; then
          local +x continue="$1"; shift
        fi
        ;;

      *)
        echo "!!! Unknown action: samples $ACTION" >&2
        exit 2
        ;;
    esac

    for name in $(da_style.cr property used) ; do
      if [[ ! -z "$continue" && "$name" < "$continue" ]]; then
        echo "=== skipping: $name" >&2
        continue
      fi

      if [[ ! -z "$save" ]]; then
        if [[ "$name" == "-ms-border-radius" ]]; then
          echo "=== Skipping: $name"
          continue=""
          continue
        fi
        echo "=== Saving: $name"
        print-page $name > specs/parser/samples/${name}.css
        continue
      fi

      echo
      print-page $name
      continue=""
    done
    ;;

  diff)
    local +x TMP_FILE_1="$(mktemp)"
    local +x TMP_FILE_2="$(mktemp)"
    da_style.cr property-list latest > "$TMP_FILE_1"
    cat "$LIST_TXT" | sort | uniq  > "$TMP_FILE_2"
    diff --ignore-all-space "$TMP_FILE_1" "$TMP_FILE_2"
    rm -f "$TMP_FILE_1" "$TMP_FILE_2"
    ;;

  family)
    {
      IFS=$'\n'
      for line in $(cat "$LIST_TXT" | grep -- "-" | cut -d"-" -f1 | sort | uniq -c -d | tr -s " ") ; do
        local +x num=$line[(ws: :)1]
        local +x word=$line[(ws: :)2]
        if [[ "$num" -gt 2 && ! -z "$word" ]]; then
          echo $word
        fi
      done
    } > "$LIST_FAMILY"
    cat "$LIST_FAMILY"
    ;;

  used)
    cat src/da_style/parser/properties.cr | grep -P '^\ *def_property' | cut -d'"' -f2 | sort
    ;;

  w3)
    {
      lynx --dump "https://www.w3.org/TR/CSS2/propidx.html" | grep -Po "]'\K[^']+"
      cat "$LIST_NON_STANDARD"
    } | sort | uniq | grep -v -P '^$'
    ;;

  *)
    echo "!!! Unknown arguments: $ORIGINAL_ARGS" >&2
    exit 1
    ;;

esac

